# Run the command 'docker-compose up' to start the services

services:
  catalog:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  order:
    build:
      context: ../order
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - CATALOG_SERVICE_URL=http://catalog:8080
