# Run the command 'docker-compose up' to start the services
version: '3.9' # Specify the version of the Docker Compose file format!

services:
  catalog:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  order:
    build:
      context: ../order # Specify the folder '../order' if they have the same root directory
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
