name: CI/CD Catalog

# Define when this workflow will run
on:
  push:
    branches:
      - main      # Trigger on pushes to main branch
  pull_request:
    branches:
      - main      # Trigger on PRs targeting main branch

jobs:
  build:
    # Specify the runner environment
    runs-on: ubuntu-24.04

    steps:
      # Step 1: Check out the repository code
      - uses: actions/checkout@v4 

      # Step 2: Configure Java Development Kit
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'     # Use Eclipse Temurin distribution
          java-version: '21'          # Specify Java version 21

      # Step 3: Cache Maven dependencies to speed up builds
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2                                               # Location of Maven cache
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}   # Cache key based on OS and pom.xml
          restore-keys: ${{ runner.os }}-m2                         # Fallback cache key (if path to cache not found)
      
      # Step 4: Build JAR and skip tests (for load testing)
      - name: Build application
        run: |    
          mvn clean package -DskipTests

      # Step 5: Start application for end-to-end tests
      - name: Start application
        run: java -jar target/CatalogApplication.jar &

      # Step 6: Confirm Catalog service is running for load testing
      - name: Wait for catalog service to start
        run: |
          timeout=300
          while ! curl -s -o /dev/null -w "%{http_code}" http://localhost:8080 | grep -q "404"
          do
            if [ $timeout -le 0 ]; then
              echo "Timed out waiting for catalog service!"
              exit 1
            fi
            echo "Waiting for catalog service to be ready..."
            sleep 5
            timeout=$((timeout - 5))
          done
          echo "Catalog service is ready!"

      # Step 7: Run Gatling load tests
      - name: Run Gatling load tests
        run: mvn gatling:test

      # Step 8: Stop order application after load testing
      - name: Stop application
        run: pkill -f 'java -jar'

      # Step 9: Run unit tests
      # Could be reordered - to run unit tests beforehand (even before packaging)
      - name: Run tests
        run: mvn test

      # Step 10: Generate JaCoCo report
      - name: Generate JaCoCo report
        run: mvn jacoco:report

      # Step 11: Upload unit test results as artifacts
      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: always()                        # Always upload test results
        with:
          name: test-reports
          path: target/surefire-reports/
          retention-days: 7
      
      # Step 12: Upload Gatling results as artifacts
      - name: Upload Gatling Results
        uses: actions/upload-artifact@v4
        with:
          name: gatling-results
          path: target/gatling

      # Step 13: Authenticate with DockerHub
      # https://hub.docker.com/u/saschavetsch
      - name: Login to DockerHub
        uses: docker/login-action@v3                    # Official Docker login action
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}   # Username from GitHub secrets
          password: ${{ secrets.DOCKERHUB_TOKEN }}      # Access token from GitHub secrets

      # Step 14: Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v3                           # Official Docker build and push action
        with:
          context: .                                                # Build context is root directory
          push: true                                                # Actually push the image
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/catalog:latest    # Image name and tag

      # Step 15: Generate and publish code coverage report
      - name: Upload JaCoCo coverage report
        uses: actions/upload-artifact@v4      # Action for publishing JaCoCo reports
        with:
          name: jacoco-report
          path: target/site/jacoco/           # Path to JaCoCo report
          retention-days: 7